### PR TITLE
Allow non-ASCII description

### LINKED ISSUE #61: Non-English description will be empty
**Describe the bug:**

If a project's description is not English, `best-of` will think it's all of _special characters_ and remove anything.

(see `remove_special_chars` called in `process_description`)

https://github.com/best-of-lists/best-of-generator/blob/a0c6d8a37b57e5cfe8a6d684ac312605d94bbedc/src/best_of/utils.py#L32-L56

**Expected behaviour:**

- **Ideal behaviour**: Only remove emoji and leave any other non-ASCII character as it is. — I guess it's too hard… (NLP needed?)
- **acceptable behaviour**: Provide an option to disable `remove_special_chars`. (I can try to make a PR if you'd like)

**Steps to reproduce the issue:**

Original description: (from [BIThesis](https://github.com/BITNP/BIThesis))

```
📖 北京理工大学非官方 LaTeX 模板集合，包含本科、研究生毕业设计模板及更多。🎉 （更多文档请访问 wiki 和 release 中的手册） 
```

Result: (in [best-of-bits](https://github.com/YDX-2147483647/best-of-bits/blob/896e32932cee0220d71fcd80470ecc1a12f05dfe/README.md?plain=1#L64))

```
LaTeX wiki release.
```

**Technical details:**

- Host Machine OS: Ubuntu in GitHub Actions.

**Possible Fix:**

**Additional context:**

### PR DESCRIPTION
**Pull request by YDX-2147483647**
**What kind of change does this PR introduce?**

- [x] Bugfix
- [x] New Feature
- [ ] Feature Improvment
- [ ] Refactoring
- [x] Documentation
- [ ] Other, please describe:

**Description:**

Add config `ascii_description` to resolves #61.

<table>
    <thead>
        <tr>
            <th>Config</th>
            <th>Description</th>
            <th>Default</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>ascii_description</code></td>
            <td>If <code>True</code>, all non-ASCII characters in the project description will be removed. Useful for
                filtering out distractive emoji, but hurtful in non-English cases. (Note: GitHub emoji commands (e.g.
                <code>:smile:</code>) are always removed.)</td>
            <td><code>True</code></td>
        </tr>
    </tbody>
</table>

Technically:
- I add a keyword argument `ascii_only: bool` to `utils.process_description`.
- Pass `config.ascii_description` to it when calling.

**Checklist:**

- [x] I have read the [CONTRIBUTING](https://github.com/best-of-lists/best-of-generator/blob/main/CONTRIBUTING.md) document.

  Sorry I can't use docker, therefore I can't run tests on my own. May I depend on the CI?

- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by YDX-2147483647** [comment]
Hi, may I ask a question?

How can I use `ascii_description` in my GitHub Actions? Or should I make a PR to [best-of-update-action](https://github.com/best-of-lists/best-of-update-action)? (I noticed that all PRs there were made by robots…)

**Comment by LukasMasuch** [comment]
@YDX-2147483647 I need to release a new version for this and then it will become accessible in the action. I will try to attempt that within the next few days.

**Comment by YDX-2147483647** [comment]
So, did you encounter difficulties? Anything I can help?

**Comment by YDX-2147483647** [comment]
Just FYI, I've worked out some tricks to test it, and everything works as expected!



**Details**:

1. I [forked the update-action repo](https://github.com/YDX-2147483647/best-of-update-action/commit/1c4d0457c6a49d5d01e4299066c35c1b47a6eb7a), and let `pip` [install from GitHub](https://pip.pypa.io/en/stable/topics/vcs-support/) directly.

2. Edit `.github/workflows/update-best-of-list.yml` in my own repo:

   ```yaml
   - name: update-best-of-list
     # uses: best-of-lists/best-of-update-action@v0.8.5
     uses: YDX-2147483647/best-of-update-action@ascii-description
   ```

3. Go to Actions in my own repo, run the workflow manually.

**Pull request merged**
